name: Release Bump

on:
  push:
    tags:
      - 'v*'  # Runs only when a tag like "v1.2.3" is pushed

jobs:
  build:
    name: Build Binary
    runs-on: macos-latest
    permissions:
      contents: write  # Add permission to create releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary
        run: |
          cargo build --release
          # Use the full tag name including 'v' prefix
          mv target/release/bump "bump-macos-${{ github.ref_name }}"
          # Create tarball
          tar -czf "bump-macos-${{ github.ref_name }}.tar.gz" "bump-macos-${{ github.ref_name }}"

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bump-macos-${{ github.ref_name }}
          path: bump-macos-${{ github.ref_name }}.tar.gz

  release:
    name: Publish GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add permission to create releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-assets/bump-macos-${{ github.ref_name }}/bump-macos-${{ github.ref_name }}.tar.gz
          generate_release_notes: true